### PR TITLE
Add Ethereum for Bip44 Path

### PR DESCRIPTION
**Pull request by Uxio0**

### CODE REVIEW

**Comment by Uxio0** [comment]
@ebellocchia Would it be possible to configure the PublicKey generation depending on the coin? https://github.com/ebellocchia/bip_utils/blob/master/bip_utils/bip32.py#L332

E.g. generation of `PrivateKey` is alright for Ethereum, but `PublicKey` is not.

**Comment by Uxio0** [comment]
> Hello, I quickly tried with ETH as a coin and the public/private extended keys are correct (I always use this website to check: https://iancoleman.io/bip39/). So, the only thing to modify is the address, because it uses a different algorithm to compute it.

You are right, I was trying to get the hash and didn't check that the `PublicKey` was compressed. It works. `Address` is what needs some adjustment.

**Comment by ebellocchia** [comment]
Ok, I'll add it together with the Ethereum checkum address (I noticed that the website is displaying this last one)

**Comment by ebellocchia** [comment]
Ok, I'll add it together with the Ethereum checkum address (I noticed that the website is displaying this last one)

**Comment by ebellocchia** [comment]
Hello, Ethereum support with addresses has been added

**Comment by Uxio0** [comment]
> Hello, Ethereum support with addresses has been added

Awesome, thank you very much! 👏 👏

**Pull request merged**
